org: stenmuchow
app: howisthesurf
service: howisthesurf
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    DATABASE_URL: ${env.DATABASE_URL}
functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
  postConfirmation:
    handler: hook/cognito.postSignupHandler
    events:
      - cognitoUserPool:
          pool: ${self:service}-${self:provider.stage}
          trigger: PostConfirmation
          existing: true
          forceDeploy: true
plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
